package com.geven.headsoccer.handler;

public class VariablesHandler {
    //String array with all the countries that is showed in the menu
    public static String countries[] = {"AFGHANISTAN","ALBANIË","ALGERIJE","AMERIKAANS-SAMOA","ANDORRA","ANGOLA","ANGUILLA","ANTIGUA EN BARBUDA","ARGENTINIË","ARMENIË","ARUBA","AUSTRALIË","AZERBEIDZJAN","BELGIË","BERMUDA","BHUTAN","BOSNIË","BRAZILIË","BULGARIJE","CAMBODJA",
            "CHILI","CHINA","COSTA RICA","CUBA","CYPRUS","DENEMARKEN","DUITSLAND","EL SALVADOR","ENGELAND","ESTLAND","FAEROER","FIJI","FILIPIJNEN","FINLAND","FRANKRIJK",
            "GABON","GEORGIE","GIBRALTAR","GOZO","GRIEKENLAND","GROENLAND","GUATEMALA","GUERNSEY","HAITI","HONDURAS","HONGARIJE","HONGKONG","IERLAND","IJSLAND",
            "INDIA","INDONESIE","IRAN","ISRAEL","ITALIE","JAMAICA","JORDANIE","KAAIMANEILANDEN","KAZACHSTAN","KIRGIZIE","KROATIE","LAOS","LETLAND",
            "LITOUWEN","LUXEMBURG","MACAU","MACEDONIE","MALDIVEN","MALEISIE","MALTA","MAN","MAROKKO","MEXICO","MOLDAVIE","MONGOLIE","MONTENEGRO",
            "NEDERLAND","NIEUW-ZEELAND",/*"NOORD-CYPRUS","NOORD-IERLAND",*/"NOORD-KOREA","NOORDELIJKE-MARIANEN","NOORWEGEN","OEKRAINE","OEZBEKISTAN",
            "PAKISTAN","PANAMA","PAPOEA-NIEUW-GUINEA","PARAGUAY","POLEN","PORTUGAL","QATAR","ROEMENIE","RUSLAND","SALOMONSEILANDEN",/*"SAN MARINO",*/
            "SAOEDI-ARABIE","SCHOTLAND","SERVIE","SINGAPORE","SLOVENIE","SLOWAKIJE","SPANJE","SURINAME","TADZJIKISTAN","THAILAND","TSJECHIE",
            "TURKIJE","TURKMENISTAN","TUVALU","URUGUAY","VANUATU","VATICAANSTAD","VERENIGDE-STATEN","VIETNAM",/*"WALES",*/"WIT-RUSLAND",
            "ZUID-AFRIKA","ZUID-KOREA","ZWEDEN","ZWITSERLAND"};
    public static String myCountry = "";                    //It's initialize to avoid a nullpointerexception

    public static String finalCompetition[];                //This variable is used to set a existing variable array to this array
    public static String computerFinalCompetition[];

    //List of teams in a country:
    public static String AFGHANISTAN[] = {"OQABAN HINDUKUSH","DE SPIN GHAR BAZAN","DE MAIWAND ATALAN","SHAHEEN ASMAYEE","TOOFAAN HARIROD","MAWJHAI AMU","DE ABASIN SAPE","SIMORGH ALBORZ"};
    public static String ALBANIË[] = {"KF LACI","KF TIRANE","FK KUKESI","KS BYLIS BALLSHI","FK PARTIZANI","FK VLLAZNIA SHKODER","KF TEUTA DURRES","KF SKENDERBEU KORCE","KS FLAMURTARI VLORE","KF TERBUNI"};
    public static String ALGERIJE[] = {"JS KABYLIE","DRB TRADJENANET","USM BLIDA","NA HUSSEIN-DEY","USM EL HARRACH","ES SETIF","CS CONSTANTINE","JS SAOURA","CR BELOUIZDAD","MC ALGER","MC ORAN","USM ALGER","ASM ORAN","MO BEJAIA","RC RELIZANE","RC ARBA"};
    public static String AMERIKAANS_SAMOA[] = {"UTULEI YOUTH","LION HEART FC","FC SKBC","VAIALA TONGAN","PANSA SC","TAFUNA JETS"};
    public static String ANDORRA[] = {"FC ENCAMP","FC LUSITANOS","UE SANTA COLOMA","UE SANT JULIA","FC SANTA COLOMA","FC ORDINO","PENYA ENCARNADA","UE ENGORDANY"};
    public static String ANGOLA[] = {"CRD DO LIBOLO","SPORT LUANDA","KABUSCORP SC","CD PRIMEIRO DE AGOSTO","GD INTERCLUBE","CD PROGRESSO","ATLETICO PETROLEOS","PROGRESSO","FC ONZE BRAVOS","GD SAGRADA EXPERANCA","ACADEMICA PETROLEOS","CLUBE DESPORTIVO","ATLETICO SPORT AVIACAO","SC PETROLEOS","CLUBE RECREATIVO","DOMANT FC"};
    public static String ANGUILLA[] = {"KICKS UNITED FC","ROARING LIONS FC","ATTACKERS FC","SALSA BALLERS FC","ALHCS SPARTAN FC","DIAMOND FC",};
    public static String ANTIGUA_EN_BARBUDA[] = {"PARHAM FC","GREENBAY HOPPERS","SAP FC","GRENADES FC","FORT ROAD FC","OTTOS RANGERS FC","OLD ROAD FC","FIVE ISLANDS FC","BASSA SC","URLINGS GOLDEN STARS"};
    public static String ARGENTINIË[] = {"BOCA JUNIORS","SAN LORENZO","CA RIVER PLATE","ROSARIO CENTRAL","RACING CLUB","CA BELGRANO","CA TIGRE","GIMNASIA","CA BANFIELD","CA LANUS","ESTUDIANTES","CA INDEPENDIENTE","CA UNION","CA OLD BOYS","CA ALDOSIVI","ARGENTINOS JUNIORS","CA SAN MARTIN","VELEZ SARSFIELD"};
    public static String ARMENIË[] = {"FC PYUNIK YEREVAN","ULISSES FC","SHIRAK FC","ALSHKERT FC","FC MIKA YEREVAN","FC BANANTS","GANDZASAR FC","FC ARARAT"};
    public static String ARUBA[] = {"SV RACING CLUB","SV BRITANNIA","BUBALI SC","SV ESTRELLA","SV DAKOTA","SV LA FAMA","SV DEPORTIVO","SV RIVERPLATE","FC SAN NICOLAAS","SV BRAZIL JUNIORS"};
    public static String AUSTRALIË[] = {"PERTH GLORY FC","CENTRAL COAST MARINERS","NEWCASTLE UNITED JETS","ADELAIDE UNITED","BRISBANE ROAR","SYDNEY FC","MELBOURNE VICTORY","WELLINGTON PHOENIX","MELBOURNE CITY","WESTERN SYDNEY"};
    public static String AZERBEIDZJAN[] = {"QARABAG AGDAM","INTER PFK","QEBELE FK","NEFTCI PFK","SIMURQ PIK","AZAL PFK","XEZER LENKERAN","SUMQAYIT","BAKI FK","ARAZ-NAXICIVAN"};
    public static String BELGIË[] = {"ANDERLECHT","GENT","CLUB BRUGGE","GENK","KORTRIJK","KV OOSTENDE","WAASLAND BEVEREN","OH LEUVEN","STANDARD LIEGE","MECHELEN","ZULTE-WAREGEM","LOKEREN","SPORTING CHARLEROI","SINT-TRUIDEN","WESTERLO","MOUSCRON-PERUWELZ",};
    public static String BERMUDA[] = {"DEVONSHIRE COUGARS","BOULEVARD BLAZERS","DANDY TOWN","NORTH VILLAGE","HAMILTON PARISH","PHC ZEBRAS","SOUTHAMPTON RANGERS","DEVONSHIRE COLTS","SOMERSET CC","ROBIN HOOD FC",};
    public static String BHUTAN[] = {"THIMPHU FC","UGYEN ACADEMY","THIMPHU CITY","FC TERTONS","BHUTAN CLEARING","PARO UNITED"};
    public static String BOSNIË[] = {"FK SARAJEVO","FK BORAC","ZRINJSKI MOSTAR","NK CELIK","NK TRAVNIK","NK SIROKI","FK OLIMPIC","FK SLOBODA","NK VITEZ","FK SLAVIJA","FK ZELJEZNICAR","FK VELEZ","FK RADNIK","FK RUDAR","FK DRINA","FK MLADOST"};
    public static String BRAZILIË[] = {"CA MINEIRO","SC CORINTHIANS","SC PALMEIRAS","SC RECIFE","SAO PAULO FC","GREMIO","FLUMINENSE","CA PARANAENSE","CHAPECOENSE AF","SC INTERNACIONAL","AA PONTE PRETA","CR FLAMENGO","CRUZEIRO EC","AVAI FC","SANTOS FC","FIGUEIRENSE FC","GOIAS EC","VASCO DA GAMA","CORITIBA FC","JOINVILLE EC"};
    public static String BULGARIJE[] = {"PFK LUDOGORETS","PFK LOKOMOTIV","PFK LITEX","PFK BEROE STARA","FK BOTEV","PFK LEVSKI","PFK CHERNO","PFK SLAVIA","PFK LOKOMOTIV","OFK PIRIN"};
    public static String CAMBODJA[] = {"BOEUNG KET","PHNOM PENH CROWN","CAMBODIAN TIGER","SVAY RIENG","NATIONAL POLICE","BUILD BRIGHT UNITED","NAGAWORLD FC","NATIONAL DEFENSE","WESTERN PHNOM","CMAC UNITED","ASIA EURO UNITED","KIRIVONG FC"};
    public static String CHILI[] = {"CSD COLO-COLO","CF UNIVERSIDAD DE CHILE","CD AUDAX ITALIANO","CD UNIVERSIDAD CONCEPCION","CD UNIVERSIDAD CATOLICA","UNION ESPANOLA","CD COBRESAL","CD HUACHIPATO","CD O HIGGINS","CD ANTOFAGASTA","CD IQUIQUE","CD SANTIAGO","CD UNION LA CALERA","CD PALESTINO","CD SAN LUIS","CDC SAN MARCOS"};
    public static String CHINA[] = {"SHANGHAI SIPG","GUANGZHOU","SHANDONG","BEIJING GUOAN","SHIJIAZHUANG","SHENGHAI GREENLAND","JIANGSU","HENAN JIANYE FC","CHANGCHUN YATAI","CHONGQING LIFAN","GUANGZHOU FC","GUIZHOU RENHE","HANGSZHOU GREENTOWN","TIANJIN TEDA","LIAONING","SHANGHAI SHENXIN",};
    public static String COSTA_RICA[] = {"CS HEREDIANO","BELEN BRIDGESTONE","LD ALAJUELENSE","DEPORTIVO SAPRISSA","CF UNIVERSIDAD","MUNICIPAL LIBERIA","AD MUNICIPAL","CS URUGUAY","CS CARTAGINES","LIMON FC","SANTOS DE GUAPILES","AD CARMELITA"};
    public static String CUBA[] = {"FC CAMAGUEY","FC CIENFUEGOS","LA HABANA","FC VILLA CLARA","FC SANTIAGO","FC GUANTANAMO","FC CIEGO","FC LAS TUNAS","FC SANCTI","FC ISLA"};
    public static String CYPRUS[] = {"APOEL FC","APOLLON FC","AS OMONIA","AEK LARNAKA","AS NEA","AS ANORTHOSIS","ERMIS FC","AEL LEMESOS","PAFOS FC","AO AYIA","AS ETHNIKOS"};
    public static String DENEMARKEN[] = {"FC KOBENHAVN","SONDERJYSKE","AALBORG BK","BRONDBY IF","FC MIDTJYLLAND","ODENSE BK","VIBORG FF","FC NORDSJAELLAND","RANDERS FC","AARHUS GF","HOBRO IK"};
    public static String DUITSLAND[] = {"BAYERN MÜNCHEN","BORUSSIA DORTMUND","HERTHA BSC","SCHALKE 04","MONCHENGLADBACH","BAYER LEVERKUSEN","FSV MAINZ","VFL WOLFSBURG","FC KOLN","FC INGOLSTADT","VFB STUTTGART","HAMBURGER SV","DARMSTADT 98","WERDER BREMEN","FC AUGSBURG","1899 HOFFENHEIM","EINTRACHT FRANKFURT", "HANNOVER 96"};
    public static String EL_SALVADOR[] = {"CD JUVENTUD","SANTA TECLA","CD AGUILA","ALIANZA FC","AD ISIDRO","CD DRAGON","CD FAS","CD UNIVERSIDAD","CD PASAQUINA","CD ATLETICO"};
    public static String ENGELAND[] = {"LEICESTER CITY","TOTTENHAM HOTSPUR","ARSENAL","MANCHESTER CITY","WEST HAM UNITED","MANCHESTER UNITED","SOUTHAMPTON","STOKE CITY","LIVERPOOL","CHELSEA","WEST BROMWICH","EVERTON","BOURNEMOUTH","WATFORD","SWANSEA CITY","SUNDERLAND","NEWCASTLE UNITED","ASTON VILLA"};
    public static String ESTLAND[] = {"TALLINNA FC","NOMME JK","FC LEVADIA","JK TRAMMEKA","JK SILLAMAE","JK NARVA","PARNU LINNAMEESKOND","PAIDE LINNAMEESKOND","JK VILJANDI"};
    public static String FAEROER[] = {"HB","B36","NSI RUNAVIK","VIKINGUR GOTA","TB TVOROYRI","IF FUGLAFJOROUR","KI","EB STREYMUR","FC SUOUROY","AB ARGIR"};
    public static String FIJI[] = {"NADI FA","SUVA FA","REWA FC","LAUTOKA FC","LABASA FC","BA FC","NADROGA FC","TAILEVU FC"};
    public static String FILIPIJNEN[] = {"CERES FC","STALLION FC","KAYA FC","SPARKS FC","GREEN ARCHERS","GLOBAL FC","ARMY FC","MANILA JEEPNEY","PACHANGA DILIMAN","TEAM SOCCEROO"};
    public static String FINLAND[] = {"HJK","FC LAHTI","FC INTER TURKU","ROVANIEMI PS","VAASAN PS","KUOPION PS","IFK MARIEHAMN","ILVES TAMPERE","HIFK SOCCER","SEINAJOEN JK","FF JARO JS","KOTKA TP"};
    public static String FRANKRIJK[] = {"PSG","AS MONACO","NICE","OLYMPIQUE LYONNAIS","STADE RENNAIS","CAEN","SAINT ETIENNE","NANTES","LILLE","ANGERS","BASTIA","OLYMPIQUE MARSEILLE","LORIENT","BORDEAUX","GUINGAMP","MONTPELLIER","REIMS","GAZELEC AJACCIO","TOULOUSE","TROYES"};
    public static String GABON[] = {"AS MANGASPORT","US BITAM","CF MOUNANA","AS PELICAN","MISSILE FC","AKANDA FC","AO CENTRE","US OYEM","PORT-GENTIL FC","FC 105","STADE MIGOVEEN","O MBILAZIAMI","AS SOLIDARITE"};
    public static String GEORGIE[] = {"DINAMO TBILISI","FC SAMTREDIA","FC DILA","FC SIONI","FC CHIKHURA","FC TSKHINVALI","DINAMO BATUMI","FC SHUKURA","FC TORPEDO","FC SABURTALO","FC KOLKHETI","FC LOKOMOTIVI","FC GURIA","FC MERANI","FC SAPOVNELA","FC ZUGDIDI"};
    public static String GIBRALTAR[] = {"LINCOLN RED IMPS","EUROPA FC","ST JOSEPHS FC","LIONS FC","LYNX FC","FC BRITANNIA XI","GLACIS UNITED FC","MANCHESTER 62 FC"};
    public static String GOZO[] = {"GHAJNSIELEM FC","XEWKIJA TIGERS","KERCEM AJAX FC","VICTORIA HOTSPURS","SK VICTORIA","ORATORY YOUTHS","ST LAWRENCE SPURS","NADUR YOUNGSTERS FC"};
    public static String GRIEKENLAND[] = {"PAE OLYMPIAKOS","PANATHINAIKOS","PAOK FC","PAE PANIONIOS","PAE PLATANIAS","PAS GIANNINA","ASTERAS TRIPOLIS","PANAITOLIKOS","ATROMITOS ATHINA","LEVADEIAKOS","SKODA XANTHI","PAE VEROIA","PANTHRAKIKOS","PAE KALLONIS","PAE KERKYRA"};
    public static String GROENLAND[] = {"B-67 NUUK","IT-79 NUUK","NAGDLUNGUAQ-48","EQALUK 54","FC MALAMUK","G-44 QUEQERTARSUAQ","NUUK IL","NAGTORALIK N-45"};
    public static String GUATEMALA[] = {"CD SUCHITEPEQUEZ","CSD MUNICIPAL","CD MARQUENSE","DESPORTIVO GUASTATOYA","DEPORTIVO MICTLAN","UNIVERSIDAD","CD MALACATECO","ANTIGUA GFC","COMUNICACIONES","CD PETAPA","COBAN IMPERIAL","CSD XELAJU MC"};
    public static String GUERNSEY[] = {"NORTHERNERS AC","VALE RECREATION","GUERNSEY ROVERS","SYLVANS SC","BELGRAVE WANDERERS","SAINT MARTINS AC","GUERNSEY RANGERS"};
    public static String HAITI[] = {"PETIT-GOAVE","FICA","AS CAVALY","RACING FC","AS CAPOISE","DON BOSCO FC","OUANAMINTHE FC","TEMPETE FC","BALTIMORE SC","RACING CLUB HAITIEN","ROULADO FC","INTER","VIOLETTE AC","AIGLE NOIR AC","AMERICA FC","AS MIREBALAIS"};
    public static String HONDURAS[] = {"CD OLIMPIA","REAL SOCIEDAD","CD MOTAGUA","CD MARATHON","REAL CD ESPANA","CDS VIDA","CD PLATENSE","HONDURAS PROGRESO","CD VICTORIA","CD PARILLAS ONE"};
    public static String HONGARIJE[] = {"FERENCVAROSI","MTK BUDAPEST","UJPEST FC","DEBRECENI","VIDEOTON FC","PAKSI FC","SZOMBATHELYI","BUDAPEST HONVED","DIOSGYORI","PUSKAS FC","VASAS FC","BEKESCSABAI"};
    public static String HONGKONG[] = {"EASTERN SALON","KITCHEE SC","SOUTH CHINA AA","REALTY WOFOO","SUN PEGASUS FC","WONG TAI SIN","YUEN LONG","BIU CHUN RANGERS","YFCMD"};
    public static String IERLAND[] = {"DUNDALK FC","DERRY CITY","GALWAY UNITED","CORK CITY","SHAMROCK ROVERS","SAINT PATRICKS","BRAY WANDERERS","BOHEMIANS FC","LONGFORD TOWN","SLIGO ROVERS","DROGHEDA UNITED","LIMERICK FC"};
    public static String IJSLAND[] = {"HAFNARFJOROUR","UMF STJARNAN","KF VALUR","UMF FJOLNIR","KR REYKJAVIK","KF VIKINGUR","IF FYLKIR","BREIOABLIK UBK","VESTMANNAEYJA","IA AKRANES","KF KEFLAVIK","LEIKNIR"};
    public static String INDIA[] = {"MOHUN BAGAN AC","BENGALURU FC","KINGFISHER","SPORTING CLUBE","MUMBAI FC","SALGAOCAR FC","SHILLONG LAJONG","DEMPO SC","KALYANI BHARAT"};
    public static String INDONESIE[] = {"GRESIK UNITED","PERSIPURA","PERSIB","PSM MAKASSAR","AREMA CRONUS","PERSERU","PERSEBAYA","SRIWIJAYA","PS BARITO PUTERA","PERSELA","PERSIJA JAKARTA","SEMEN PADANG","PUSAMANIA","PERSIRAM","PELITA","PS MITRA KUKAR","BALI UNITED","PERSIBA"};
    public static String IRAN[] = {"ESTEGHLAL TEHERAN","ESTEGHLAL FC","PERSEPOLIS","ZOB AHAN","TRACTOR SAZI","SAIPA FC","GOSTARESH FOOLAD","SABA QOM","PADIDEH SHAANDIZ","FOOLAD MOBARAKEH","MALAVAN BANDAR","SIAH FC"};
    public static String ISRAEL[] = {"HAPOEL TEL AVIV","MACCABI TEL AVIV","BEITAR JERUSALEM","HAPOEL","IHOUD BNEI","MACCABI HAIFA","MACCABI PETAH","HAPOEL IRONI ACRE","HAPOEL TEL AVIV","HAPOEL IRONI","HAPOEL HAIFA","MACCABI NETANYA"};
    public static String ITALIE[] = {"JUVENTUS","NAPOLI","AS ROMA","FIORENTINA","INTERNAZIONALE","AC MILAN","US SASSUOLO CALCIO","LAZIO","AC CHIEVO VERONA","BOLOGNA FC","EMPOLI FC","GENOA CFC","TORINO FC","ATALANTA BC","UC SAMPDORIA","UDINESE CALCIO","CARPI FC","US CITTA","FROSINONE CALCIO","HELLAS VERONA"};
    public static String JAMAICA[] = {"ARNETT GARDENS","MONTEGO BAY UNITED","HUMBLE LIONS","HARBOUR VIEW","BOYS TOWN","TIVOLI GARDENS","RENO FC","CAVALIER SC","RIVOLI UNITED","WATERHOUSE FC","BARBICAN FC","SPORTING CENTRAL"};
    public static String JORDANIE[] = {"AL WEHDAT SC","AL FAISALY","AL-AHLI SC","SHABAB AL-ORDON","AL RAMTHA","AL JAZEERA CLUB","AL-SAREEH SC","AL HUSSEIN SC","THAT RAS CLUB","AL-BAQA A SC","AL-ITTIHAD SC","HASAN CLUB"};
    public static String KAAIMANEILANDEN[] = {"SCHOLARS INTERNATIONAL","ELITE SC","CAYMAN ATHLETICS","SUNSET FC","BODDEN TOWN FC","GEORGE TOWN","ROMA UNITED","CAYMAN BRAC"};
    public static String KAZACHTSTAN[] = {"FK IRTYSH","FK ASTANA","FK TARAZ","FK TOBOL","FK ORDABASY","FK ZHETYSU","FK ATYRAU","KAIRAT ALMATY","FK SHAKHTYOR","FK OKZHETPES","FK KAISAR"};
    public static String KIRGIZIE[] = {"FK ALAY OSH","FK DORDOI","FK ALA-TOO","FK ALGA","FK ABDYSH-ATA","KG UNITED"};
    public static String KOSOVO[] = {"KF HAJVALIA","KF FERRONIKELI","KF BESA PEJE","KF TREPCA","KF DRENICA","DRITA KF","KF PRISHTINA","KF LLAMKOS","KF ISTOGU","KF FERIZAJ","KF TREPCA MITROVICE","KF VELLAZNIMI"};
    public static String KROATIE[] = {"DINAMO ZAGREB","HNK RIJEKA","HAJDUK SPLIT","RNK SPLIT","NK LOKOMOTIVA","INTER ZAPRESIC","NK SLAVEN","NK OSIJEK","NK ISTRA","NK ZAGREB"};
    public static String LAOS[] = {"YOUNG ELEPHANT","LAO TOYOTA","SAVAN FC","EASTERN STAR","EZRA FC","LANEXANG UNITED","LAO POLICE","ELECTRICITE","CHAMPASAK UNITED","HOANG ANH","SHB VIENTIANE"};
    public static String LETLAND[] = {"FK SPARTAKS JURMALA","FK JELGAVA","FS METTA","FK VENTSPILS","FK LIEPAJA","BFC DAUGAVPILS","FB GULBENE","SKONTO FC"};
    public static String LITOUWEN[] = {"FD ZALGIRIS","FK TRAKAI","FK ATLANTAS","FK SPYRIS","FK STUMBRAS","FK UTENIS","FK KLAIPEDOS","FK SIAULIAI"};
    public static String LUXEMBURG[] = {"F91 DUDELANGE","FOLA ESCH","DIFFERDANGE 03","JEUNESSE DESCH","PROGRES NIEDERCORN","UNA STRASSEN","RACING UNION LUXEMBURG","RM HAMM BENFICA","RUMELANGE","MONDORF LES BAINS","ETZELLA ETTELBRUCK","VICTORIA ROSPORT","CS GREVENMACHER"};
    public static String MACAU[] = {"CASA BENFICA","SPORTING CLUBE DE MACAU","CHAO PAK KEI","WINDSOR ARCH KA I","CD MONTE CARLO","LAI CHI","POLICIA","CHUAC LUN","CD CASA","MFA DEVELOPMENT"};
    public static String MACEDONIE[] = {"FK VARDAR","KF SHKENDIJA","FK SHKUPI","SILEKS FK","FK RABOTNICKI","KF RENOVA","FK HORIZONT","FK BREGALNICA","FK MLADOST CAREV","FK METALURG"};
    public static String MALDIVEN[] = {"NEW RADIANT SC","TC SPORTS CLUB","CLUB EAGLES","MAZIYA SRC","VICTORY SC","CLUB VALENCIA","BG SPORTS CLUB","BG SPORTS CLUB","MAHIBADHOO ZJ"};
    public static String MALEISIE[] = {"JOHOR DARUL","KL FELDA UNITED","FA SELANGOR","TERENGGANU FA","KELANTAN FA","POLIS DI-RAJA","PERAK FA","FA SARAWAK","PAHANG FA","ATM FA","LIONS XII","SIME DARBY FC"};
    public static String MALTA[] = {"VALLETTA FC","BIRKIRKARA FC","HIBERNIANS FC","BALZAN FC","FLORIANA FC","TARXIEN RAINBOWS","SLIEMA WANDERERS","PEMBROKE ATHLETA","SAINT ANDREWS","MOSTA FC","QORMI FC","NAXXAR LIONS FC"};
    public static String MAN[] = {"CASTLETOWN MFC","CORINTHIANS AFC","DHSOB AFC","LAXEY AFC","MAROWN AFC","PEEL AFC","RAMSEY AFC","RUSHEN UNITED","ST GEORGES AFC","ST JOHNS UNITED","ST MARYS AFC","UNION MILLS FC"};
    public static String MAROKKO[] = {"WYDAD ATHLETIC CLUB","FUS RABAT","RAJA AC","MOGHREB ATHLETIC","RSB BERKANE","HUS AGADIR","KENITRA AC","CHABAB RIF","FAR RABAT","KAWKAB AC","OC SAFI","DHJ EL-JADIDA","MAGHREB AS","OC KHOURIGBA","CHABAB ATLAS","IZ KHEMISSET","RSB BERKANE"};
    public static String MEXICO[] = {"CF MONTERREY","CF PACHUCA","CF AMERICA","CLUB LEON","CRUZ AZUL","CLUB SANTOS LAGUNA","TIGRES","CLUB TIJUANA","PUMAS","PUEBLA FC","MONARCAS MOREILIA","CD GUADALAJARA","CHIAPAS FC","DEPORTIVO TOLUCA","QUERETARO FC","CD TIBURONES ROJOS","ATLAS FC","DORADOS"};
    public static String MOLDAVIE[] = {"FC DACIA","FC SHERIFF","FC ZIMBRU","FC ZARIA","DINAMO-AUTO","MILSAMI ORHEI","FC ACADEMIA","FC SAXAN GAGAUZ YERI"};
    public static String MONGOLIE[] = {"ERCHIM CLUB","FC ULANBAATAR","FC SELENGE PRESS","KHOROMKHON CLUB","KHANGARID CLUB","ULAANBAATAR UNIVERSITY","FC DEREN-SUMIDA","MAZAALAYNUUD CLUB","SOYOMBRYN BARSUUD"};
    public static String MONTENEGRO[] = {"FK MLADOST PODGORICA","FK RUDAR","FK BUDUCNOST","FK BOKELJ","FK SUTJESKA","FK DECIC","OFK GRBALJ","FK LOVCEN","FK ZETA","OFK PETROVAC","FK ISKRA","FK MORNAR"};
    public static String NEDERLAND[] = {"PSV","AJAX","FEYENOORD","AZ","SC HEERENVEEN","FC TWENTE","VITESSE","NEC","RODA JC","FC UTRECHT","HERACLES ALMELO","FC GRONINGEN","ADO DEN HAAG","PEC ZWOLLE","WILLEM II","SC CAMBUUR","DE GRAAFSCHAP","EXCELSIOR"};
    public static String NIEUW_ZEELAND[] = {"AUCKLAND CITY","HAWKES BAY UNITED","TEAM WELLINGTON","CANTERBURY UNITED","WAIBOP UNITED","WAITAKERE UNITED","PHOENIX FC","SOUTHERN UNITED"};
    public static String NOORD_CYPRUS[] = {"CETINKAYA TURK","LEFKE TSK","KUCUK KAYMAKLI","CIHANGIR GSK","DOGAN TURK","MAGUSA TURK","TURK OCAGI","YENICAMI AK","YENI BOGAZICI","BOSTANCI BAGCIL","MORMENEKSE","DEGIRMENLIK","LARNAKA GENCLER","BINATLI YILMAZ"};
    public static String NOORD_IERLAND[] = {"CRUSADERS FC","GLENTORAN FC","CLIFTONVILLE","COLERAINE FC","GLENAVON FC","LINFIELD FC","BALLINAMALLARD","BALLYMENA UNITED","DUNGANNON SWIFTS","PORTADOWN FC","WARRENPOINT TOWN","CARRICK RANGERS"};
    public static String NOORD_KOREA[] = {"4 25 SPORTS GROUP","AMROKGANG","JADONGCHA","LOCOMOTIVE SPORTS GROUP","PYONGYANG CITY","RIMYONGSU"};
    public static String NOORDELIJKE_MARIANEN[] = {"PAIRE FC","KOREAN FOOTBALL","TANHOLDINGS FC","MP UNITED FC","INTER GODFATHERS","WILD BILLS"};
    public static String NOORWEGEN[] = {"FK HAUGESUND","FK BODO","VIKING FK","MOLDE FK","ODDS BK","ROSENBORG BK","AALESUNDS FK","LILLESTROM SK","IK START","TROMSO IL","STROMSGODSET IF","SARPSBORG 08","STRABAEK FOTBALL","VALERENGA IF","SANDEFJORD FOTBALL"};
    public static String OEKRAINE[] = {"FK DYNAMO KYIV","FK SHAKHTAR DONETSK","FK ZORJA","FK DNIPRO","FK VORSKLA","FK OLEKSANDRIYA","FK KARPATY","FK OLIMPIK DONETSK","FK METALIST","FK VOLYN","FK HOVERLA","FK CHERNOMORETS","METALURH FK"};
    public static String OEZBEKISTAN[] = {"FK PAKHTAKOR","LOKOMOTIV TOSHKENT","NASAF QARSHI","PFK METALOURG","BUNYODKOR PFK","PFK QIZILQUM","BUXORO FK","FK NEFTCHI","PFK NAVBAHOR","PFK JIZZAX","FK MASH","PFK ANDIJON","OLMALIQ FK"};
    public static String OOSTENRIJK[] = {"FC RED BULL","SK RAPID","FK AUSTRIA","FC ADMIRA","SV MATTERSBURG","SK STURM GRAZ","SH RHEINDORF","WOLFSBERGER AC","SV RIED","SV GRODIG"};
    public static String PAKISTAN[] = {"K-ELECTRIC FC","PAKISTAN ARMY","PAKISTAN AIR FORCE","PIA FC","WAPDA FC","KRL FC","NBP FC","MUSLIM FC","KARACHI","FC CHAMAN","PAKISTAN RAILWAYS"};
    public static String PANAMA[] = {"TAURO FC","CD ARABE UNIDO","CD ATLETICO CHIRIQUI","CHORRILLO FC","CD PLAZA AMADOR","SAN FRANCISCO FC","ADF SPORTING","CHEPO FC","ALIANZA"};
    public static String PAPOEA_NIEUW_GUINEA[] = {"HEKARI UNITED","LAE CITY DWELLERS","ADMIRALTY PELIAU","BESTA PNG UNITED","FC PORT","MADANG FC","ORO FC"};
    public static String PARAGUAY[] = {"CLUB SOL DE AMERICA","CLUB LIBERTAD","CLUB GENERAL DIAZ","CLUB RUBIO","CS LUQUENO","CLUB OLIMPIA","CLUB NACIONAL","CLUB CERRO","CD CAPIATA","CLUB GUARANI","CD SANTANI","CS SAN LORENZO"};
    public static String POLEN[] = {"LEGIA WARSZAWA","GKS PIAST","MKS CRACOVIA","MKS POGON","ZAGLEBIE LUBIN","KKS LECH","KS RUCH","KS LECHIA","JAGIELLONIA","WISLA KRAKOW","KS TERMALICA","TS PODBESKIDZIE","KORONA KIELCE","GKS GORNIK","WKS SLASK","ZABRZE"};
    public static String PORTUGAL[] = {"SPORT LISBOA","SPORTING PORTUGAL","FC PORTO","SPORTING CLUB BRAGA","FC AROUCA","RIO AVE","FC PACOS","ESTORIL PRAIA","VITORIA FC","MOREIRENSE FC","CF UNIAO","BOAVISTA FC","AA COIMBRA","CD TONDELA"};
    public static String QATAR[] = {"EL JAISH SC","AL SADD SC","LEKHWIYA SC","UMM SALAL SC","AL ARABI SC","AL SAILIYA SC","AL GHARAFA SC","AL AHLI SC","AL KHOR SC","AL WAKRAH SC","AL-KHARAITIYATH SC","QATAR SC","AL AHLI SC","AL SHAHANIYA SC","AL SHAMAL SC"};
    public static String ROEMENIE[] = {"STEAUA BUCURESTI","FC ASTRA","CS PANDURII","FC DINAMO","ASA TARGU","FC VIITORUL","CS UNIVERSITATEA","CS CONCORDIA","FC VOLUNTARI","FC CFR","SC FC PETROLUL","CSM STUDENTESC","FC SA BOTOSANI","ACS POLI"};
    public static String RUSLAND[] = {"CSKA MOSKVA","FK ROSTOV","FK LOKOMOTIV MOSKVA","FK ZENIT","SPARTAK MOSKVA","RFK TEREK","FK KRASNODAR","FK URAL","DINAMO MOSKVA","FK RUBIN KAZAN","FK AMKAR","FK KRYLIA","FK KUBAN","FK UFA","FK MORDOVIA","FK ANZHI"};
    public static String SALOMONSEILANDEN[] = {"HANA FC","MALAITA KINGZ","REAL KAKAMORA","WESTERN UNITED","KOLOALE FC","MARIST FIRE FC","KOSSA FC","SOLOMON WARRIORS","X-BEAM FC"};
    public static String SAN_MARINO[] = {"TRE PENNE","SP TRE FIORI","SS FOLGORE","FC DOMAGNANO","FC FIORENTINO","SS VIRTUS","SS MURATA","SP LA FIORITA","SS PENNAROSSA","AC JUVENES","AC LIBERTAS","SP CAILUNGO","SP COSMOS","SC FAETANO","SAN GIOVANNI"};
    public static String SAOEDI_ARABIE[] = {"AL-AHLI SAUDI","AL HILAL SAUDI","AL-ITTIHAD","AL-TAAWON FC","AL-SHABAB FC","AL-KHALEEJ CLUB","AL-FATEH FC","AL-FAISALY FC","AL NASSR FC","NAJRAN SC","ALRAED CLUB","HAJER FC","AL-ITTIHAD","AL-ORUBAH FC"};
    public static String SCHOTLAND[] = {"CELTIC FC","ABERDEEN FC","HEART OF MIDLOTHIAN","ST JOHNSTONE","MOTHERWELL FC","ROSS COUNTY","DUNDEE FC","PATRICK THISTLE","INVERNESS CALEDONIAN","HAMILTON FC","KILMARNOCK FC","DUNDEE UNITED"};
    public static String SERVIE[] = {"FK CRVENA","FK PARTIZAN","FK BORAC CACAK","FK CUKARICIKI","FK RADNICKI","FK VOZDOVAC","FK RADNIK SURDULICA","FK JAVOR","FK MLADOST LUCANI","FK METALAC","OFK BEOGRAD","FK SPARTAK SUBOTICA","FK RAD BEOGRAD","FK JAGODINA"};
    public static String SHETLAND[] = {"LERWICK SPURS","LERWICK CELTIC","WHALSAY FC","DELTING FC","DELTING FC","WHITEDALE FC","LERWICK THISTLE","SCALLOWAY FC","NESS UNITED","PETROFAC FC"};
    public static String SINGAPORE[] = {"HOUGANG UNITED","TAMPINES ROVERS","ALBIREX NIIGATA","WARRIORS FC","DPMM FC","GEYLANG INTERNATIONAL","HOME UNITED","BALESTIER KHALSA","COURTS YOUNG LIONS"};
    public static String SLOVENIE[] = {"NK OLIMPIJA LJUBLJANA","NK MARIBOR","NK DOMZALE","ND GORICA","NK ZAVRC","NK CELJE","FC LUKA KOPER","NK KRKA","NK RUDAR","NK KRSKO"};
    public static String SLOWAKIJE[] = {"FK AS TRENCIN","SLOVAN BRATISLAVA","TJ SPARTAK MYJAVA","MFK RUZOMBEROK","MSK ZILINA","FC DAC","FC SPARTAK","FK SENICA","FC VION","FO ZP SPORT","MFK ZEMPLIN","MFK SKALICA"};
    public static String SPANJE[] = {"FC BARCELONA","CLUB ATLETICO MADRID","REAL MADRID","VILLARREAL CF","SEVILLA FC","RC CELTA","ATHLETIC CLUB","MALAGA CF","SD EIBAR","RC DEPORTIVO","REAL SOCIEDAD DE FUTBOL","RCD ESPANYOL","VALENCIA CF","REAL BETIS","UD LAS PALMAS","RAYO VALLECANO","GRANADA CF","GESTAFE CF","REAL SPORTING","LEVANTE UD"};
    public static String SURINAME[] = {"FC INTER MOENGO","SV NOTCH","SV WALKING BOYZ","SV LEO VICTOR","SV EXCELSIOR","SV TRANSVAAL","SV BOTOPASIE","TAKDIER BOYS","SCSV BOMASTAR","SV SNL"};
    public static String TADZJIKISTAN[] = {"FK ISTIKLOL","FK KHUJAND","FK RAVSHAN","FK REGAR","FK XAYR","CSKA PAMIR","FK BARKI","FK VAKHSH","FK DALERON","FK PARVOZ"};
    public static String THAILAND[] = {"BANGKOK GLASS","BANGKOK UNITED","SCG MUANGTHONG","RATCHABURI MITRPHOL","CHIANGRAI UNITED","BURIRAM UNITED","SUPHANBURI","CHONBURI FC","SISAKET FC","NAKHON FC","ARMY UNITED","BEC TERO SASANA","OSOTSPA","CHAINAT HORNBILL","SIAM NAVY FC","GULF SARABURI","TOT SC"};
    public static String TSJECHIE[] = {"FC VIKTORIA","SPARTA PRAHA","FK MLADA","FC SLOVAN","SLAVIA PRAHA","FC ZBROJOVKA","FC SLOVACKO","FK BAUMIT","FK TEPLICE","FK DUKLA","BOHEMIANS","FC FASTAV","FK PRIBRAM","FC VYSOCINA","SK SIGMA","FC BANIK"};
    public static String TURKIJE[] = {"BESIKTAS JK","FENERBAHCE SK","TORKU KONYASPOR","ISTANBUL BASAKSEHIR","GALATASARAY SK","OSMANLISPOR FK","AKHISAR BELEDIYE","KASIMPASA SK","BURSASPOR K","GENCLERBIRLIGI SK","GAZIANTEPSPOR K","ANTALYASPOR PFT","TRABZONSPOR K","CAYKUR RIZESPOR K","KAYSERISPOR K","MEDICANA K","MERSIN IDMAN","ESKISEHIRSPOR K"};
    public static String TURKMENISTAN[] = {"FK AHAL","FK BALKAN","FK ENERGETIK","FK MERW MARY","FK ASGABAT","FK SAGADAM","HTTU ASGABAT","FK ALTYN","FK DASOGUZ","FK HAZYNA"};
    public static String TUVALU[] = {"NAUTI FC","FC TOFAGA","FC NANUMAGA","LAKENA UNITED","FC MANU LAEVA","NUI FC","TAMANUKU","FC NIUTAO"};
    public static String URUGUAY[] = {"CA PENAROL","CA CERRO","CA FENIX","IASA","CLUB NACIONAL FOOTBALL","RACING CLUB MONTEVIDEO","CCYD EL TANQUE","DEFENSOR SC","MONTEVIDEO WANDERERS","CA JUVENTUD","CA RENTISTAS","CA RIVER PLATE","DANUBIO FC","CA ATENAS","CA FENIX","RAMPLA JUNIORS","TACUAREMBO FC"};
    public static String VANUATU[] = {"AMICALE FC","ERAKOR GOLDEN STAR","IFIRA BLACK BIRD","NARAK TEGAPU","SHEPHERDS UNITED","SPIRIT 08","TAFEA FC","TUPUJI IMERE"};
    public static String VATICAANSTAD[] = {"SAN PIETRO TEAM","DIRTEL TEAM","SANTOS VATICANI","FC GUERDIA","FORTITUDO 2007","MUSEI VATICANI","SS PIETRO E PAOLO"};
    public static String VERENIGDE_STATEN[] = {"SPORTING KANSAS CITY","FC DALLAS","LOS ANGELES GALAXY","VANCOUVER WHITECAPS","SAN JOSE EARTHQUAKES","REAL SALT LAKE","HOUSTON DYNAMO","PORTLAND TIMBERS","COLORADO RAPIDS","SEATTLE SOUNDERS","MONTREAL IMPACT","PHILADELPHIA UNION","ORLANDO CITY","NEW YORK CITY","TORONTO FC","NEW ENGLAND REVOLUTION","NEW YORK RED BULLS","CHICAGO FIRE","DC UNITED SC","COLUMBUS CREW"};
    public static String VIETNAM[] = {"CLB HAI PHONG","SHB DA NANG","CLB BECAMEX","CLB CAN THO","CLB DONG NAI","CLB DONG TAM","CLB DONG THAP","CLB HA NOI","CLB HOANG ANH","CLB QNK","CLB SANNA KHANH","CLB SONG LAM","CLB THAN QUANG","CLB THANH"};
    public static String WALES[] = {"GAP CONNAHS","BALA TOWN FC","THE NEW SAINTS","LLANDUDNO FC","NEWTOWN AFC","AIRBUS UK","ABERYSTWYTH TOWN","CARMARTHEN TOWN","PORT TALBOT","BANGOR CITY","HAVERFORDWEST COUNTY","RHYL FC"};
    public static String WIT_RUSLAND[] = {"SFK SLUTSK","BATE BORISOV","DINAMO MINSK","NAFTAN NOVOPOLATSK","SHAKHTYOR SOLIGORSK","FK TORPEDO","NEMAN GRODNO","FK MINSK","BELSHINA BOBRUISK","FK SLAVIYA-MOZYR","HRANIT MIKASEVICHY","DINAMO BREST","FK VITEBSK","FK GOMEL"};
    public static String ZUID_AFRIKA[] = {"MAMELODI SUNDOWNS","BIDVEST WITS","PLATINUM STARS","KAIZER CHIEFS","BLACK ACES","CHIPPA UNITED","ORLANDO PIRATES","FREE STATE STARS","AJAX CAPE TOWN","SUPERSPORT UNITED","GOLDEN ARROWS","BLOEMFONTEIN CELTIC","POLOKWANE CITY","JOMO COSMOS","UNIVERSITY OF PRETORIA","MARITZBURG UNITED"};
    public static String ZUID_KOREA[] = {"POHANG STEELERS","SEONGNAM FC","GWANGJU FC","JEONBUK","FC SEOUL","JEJU UNITED","JEONNAM DRAGONS","SUWON","ULSAN HYUNDAI","INCHEON UNITED","BUSAN IPARK","DAEJEON"};
    public static String ZWEDEN[] = {"BK HACKEN","DJURGARDENS IF","GEFLE IF","AIK FOTBOLL","HELSINGSBORGS IF","IF ELFSBORG","IFK GOTEBORG","KALMAR FF","MALMO  FF","OREBRO SK","HAMMARBY IF","IFK NORRKOPING","FALKENBERGS FF","ATVIDABERGS FF","HALMSTADS BK"};
    public static String ZWITSERLAND[] = {"FC BASEL","BSC YOUNG BOYS","GRASSHOPPER CLUB","FC SION","FC ST GALLEN","FC THUN","FC LUZERN","FC ZURICH","FC LUGANO","FC VADUZ"};

//MAROKKO,MEXICO,MOLDAVIE,PANAMA,PORTUGAL,SAOEDI ARABIE,SCHOTLAND,SERVIE,THAILAND,TURKIJE




    //Set the home team and the away team. The home team is myTeam and the away team is computerTeam. :
    public static String myTeam;
    public static String computerTeam;
    public static int positionInFinalCompetition;
    public static int positionInFinalComputerCompetition;
    public static int lenghtPositionInFinalCompetition;
    public static int lengthPositionInFinalComputerCompetition;

    public VariablesHandler(){
        myTeam = "";
        computerTeam = "";
    }
}
